# Rotate logs in /delayed_logs and /searcher_logs daily,
# keeping 5 old copies. Use copytruncate so tail
# doesn't lose its file handles.

/persistent/searcher_logs/*.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 2G
}

/run/lighthouse_logs/*.log {
    hourly
    rotate 24
    compress
    delaycompress
    missingok
    notifempty
    create 640 lighthouse-logs lighthouse-logs
    maxsize 100M
    copytruncate
}